from .travel_prompt import SYSTEM_TEMPLATE
from .ticket_prompt import REASON_TEMPLATE as TICKET_REASON_TEMPLATE
from .ticket_prompt import OBSEVATION_TEMPLATE as TICKET_OBSEVATION_TEMPLATE
from .ticket_prompt import JUDGE_REASON_TEMPLATE as TICKET_JUDGE_REASON_TEMPLATE
from .ticket_prompt import CONTENT_TO_TOOL_TEMPLATE as TICKET_CONTENT_TO_TOOL_TEMPLATE
from .amusement_prompt import SYSTEM_PLAN_TEMPLATE as AMUSEMENT_SYSTEM_PLAN_TEMPLATE
from .amusement_prompt import SYSYRM_REPLAN_TEMPLATE as AMUSEMENT_SYSYRM_REPLAN_TEMPLATE
from .amusement_prompt import SYSTEM_JUDGE_TEMPLATE as AMUSEMENT_SYSTEM_JUDGE_TEMPLATE
from .amusement_prompt import EXECUTE_TEMPLATE as AMUSEMENT_EXECUTE_TEMPLATE
from .amusement_prompt import SUMMARY_PROMPT as AMUSEMENT_SUMMARY_PROMPT
__ALL__ = ["SYSTEM_TEMPLATE",
            "TICKET_REASON_TEMPLATE",
            "TICKET_OBSEVATION_TEMPLATE",
            "TICKET_JUDGE_REASON_TEMPLATE",
            "TICKET_CONTENT_TO_TOOL_TEMPLATE",
            'AMUSEMENT_SYSTEM_PLAN_TEMPLATE',
            'AMUSEMENT_SYSYRM_REPLAN_TEMPLATE',
            'AMUSEMENT_SYSTEM_JUDGE_TEMPLATE',
            'AMUSEMENT_SUMMARY_PROMPT'
            ]