# Amusement Agent主流程Prompts
from .amusement_prompt import SYSTEM_PLAN_TEMPLATE as AMUSEMENT_SYSTEM_PLAN_TEMPLATE
from .amusement_prompt import SYSYRM_REPLAN_TEMPLATE as AMUSEMENT_SYSYRM_REPLAN_TEMPLATE
from .amusement_prompt import SYSTEM_JUDGE_TEMPLATE as AMUSEMENT_SYSTEM_JUDGE_TEMPLATE
from .amusement_prompt import EXECUTE_TEMPLATE as AMUSEMENT_EXECUTE_TEMPLATE
from .amusement_prompt import EXECUTE_SINGLE_TASK_TEMPLATE as AMUSEMENT_EXECUTE_SINGLE_TASK_TEMPLATE
from .amusement_prompt import SUMMARY_PROMPT as AMUSEMENT_SUMMARY_PROMPT
from .amusement_prompt import COORDINATOR_TASK_DISPATCH_TEMPLATE as AMUSEMENT_COORDINATOR_TASK_DISPATCH_TEMPLATE

# 反馈调整模式专用 Prompts
from .amusement_prompt import SYSTEM_PLAN_FEEDBACK_TEMPLATE as AMUSEMENT_SYSTEM_PLAN_FEEDBACK_TEMPLATE
from .amusement_prompt import SYSYRM_REPLAN_FEEDBACK_TEMPLATE as AMUSEMENT_SYSYRM_REPLAN_FEEDBACK_TEMPLATE

# 子Agent Prompts
from .amusement_prompt import (
    SUB_AGENT_SUMMARY_TASK_PROMPT,
    SUB_AGENT_QUERY_TASK_PROMPT,
    TASK_COMPLETION_CHECK_PROMPT,
    EXTRA_TOOL_CALL_GUIDANCE_PROMPT,
    TRANSPORT_AGENT_SUMMARY_TASK_PROMPT,
    TRANSPORT_AGENT_QUERY_TASK_PROMPT,
    MAP_AGENT_SUMMARY_TASK_PROMPT,
    MAP_AGENT_QUERY_TASK_PROMPT,
    SEARCH_AGENT_SUMMARY_TASK_PROMPT,
    SEARCH_AGENT_QUERY_TASK_PROMPT,
    FILE_AGENT_SUMMARY_TASK_PROMPT,
    FILE_AGENT_QUERY_TASK_PROMPT,
    WEATHER_AGENT_SUMMARY_TASK_PROMPT,
    WEATHER_AGENT_QUERY_TASK_PROMPT,
    HOTEL_AGENT_SUMMARY_TASK_PROMPT,
    HOTEL_AGENT_QUERY_TASK_PROMPT
)

__ALL__ = [
            'AMUSEMENT_SYSTEM_PLAN_TEMPLATE',
            'AMUSEMENT_SYSYRM_REPLAN_TEMPLATE',
            'AMUSEMENT_SYSTEM_JUDGE_TEMPLATE',
            'AMUSEMENT_SUMMARY_PROMPT',
            'AMUSEMENT_EXECUTE_SINGLE_TASK_TEMPLATE',
            'AMUSEMENT_COORDINATOR_TASK_DISPATCH_TEMPLATE',
            'AMUSEMENT_SYSTEM_PLAN_FEEDBACK_TEMPLATE',
            'AMUSEMENT_SYSYRM_REPLAN_FEEDBACK_TEMPLATE',
            'SUB_AGENT_SUMMARY_TASK_PROMPT',
            'SUB_AGENT_QUERY_TASK_PROMPT',
            'TASK_COMPLETION_CHECK_PROMPT',
            'EXTRA_TOOL_CALL_GUIDANCE_PROMPT',
            'TRANSPORT_AGENT_SUMMARY_TASK_PROMPT',
            'TRANSPORT_AGENT_QUERY_TASK_PROMPT',
            'MAP_AGENT_SUMMARY_TASK_PROMPT',
            'MAP_AGENT_QUERY_TASK_PROMPT',
            'SEARCH_AGENT_SUMMARY_TASK_PROMPT',
            'SEARCH_AGENT_QUERY_TASK_PROMPT',
            'FILE_AGENT_SUMMARY_TASK_PROMPT',
            'FILE_AGENT_QUERY_TASK_PROMPT',
            'WEATHER_AGENT_SUMMARY_TASK_PROMPT',
            'WEATHER_AGENT_QUERY_TASK_PROMPT',
            'HOTEL_AGENT_SUMMARY_TASK_PROMPT',
            'HOTEL_AGENT_QUERY_TASK_PROMPT'
            ]